language: python

python:
- 2.7

install:
- pip install -r requirements.txt
- pip install fabric pytest-django pytest-xdist ijson coveralls coverage
- python manage.py migrate

script:
- fab test
after_success:
  coveralls
